# coding: utf-8

"""
    digital-twin-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from dhicn_digital_twin_service.configuration import Configuration


class BoundaryConfigPointItem(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'data_source': 'str',
        'indicator_id': 'str'
    }

    attribute_map = {
        'data_source': 'dataSource',
        'indicator_id': 'indicatorId'
    }

    def __init__(self, data_source=None, indicator_id=None, local_vars_configuration=None):  # noqa: E501
        """BoundaryConfigPointItem - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._data_source = None
        self._indicator_id = None
        self.discriminator = None

        self.data_source = data_source
        if indicator_id is not None:
            self.indicator_id = indicator_id

    @property
    def data_source(self):
        """Gets the data_source of this BoundaryConfigPointItem.  # noqa: E501

        数据源，包括Measure、Forecast等 data source like \"Measure\", \"Forecast\", etc.  # noqa: E501

        :return: The data_source of this BoundaryConfigPointItem.  # noqa: E501
        :rtype: str
        """
        return self._data_source

    @data_source.setter
    def data_source(self, data_source):
        """Sets the data_source of this BoundaryConfigPointItem.

        数据源，包括Measure、Forecast等 data source like \"Measure\", \"Forecast\", etc.  # noqa: E501

        :param data_source: The data_source of this BoundaryConfigPointItem.  # noqa: E501
        :type: str
        """

        self._data_source = data_source

    @property
    def indicator_id(self):
        """Gets the indicator_id of this BoundaryConfigPointItem.  # noqa: E501

        设备指标ID device indicator id  # noqa: E501

        :return: The indicator_id of this BoundaryConfigPointItem.  # noqa: E501
        :rtype: str
        """
        return self._indicator_id

    @indicator_id.setter
    def indicator_id(self, indicator_id):
        """Sets the indicator_id of this BoundaryConfigPointItem.

        设备指标ID device indicator id  # noqa: E501

        :param indicator_id: The indicator_id of this BoundaryConfigPointItem.  # noqa: E501
        :type: str
        """

        self._indicator_id = indicator_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BoundaryConfigPointItem):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BoundaryConfigPointItem):
            return True

        return self.to_dict() != other.to_dict()
