class BaseHackermanError(Exception): ...


class BaseConfigError(BaseHackermanError): ...


class InvalidConfigError(BaseConfigError): ...


class ConfigNotFoundError(BaseConfigError): ...


class PromptNotFoundError(BaseConfigError): ...
