# Generated via: macrotype macrotype -o stubs
# Do not edit by hand
from typing import Any, Callable

_OVERLOAD_REGISTRY: dict[str, dict[str, list[Callable]]]

def _ORIG_GET_OVERLOADS(func: Callable) -> list[Callable]: ...

def _ORIG_OVERLOAD(func: Callable) -> Callable: ...

def overload(func: Callable) -> Callable: ...

def get_overloads(func: Callable) -> list[Callable]: ...

def clear_registry() -> None: ...

def patch_typing(): ...

def get_caller_module(level: int) -> str: ...

def set_module(obj: Any, module: str) -> None: ...

def emit_as(name: str): ...

def make_literal_map(name: str, mapping: dict[str | int, str | int]): ...
