from amsdal_models.classes.data_models.constraints import UniqueConstraint
from amsdal_models.classes.model import Model
from amsdal_utils.models.enums import ModuleType
from typing import Any, ClassVar

class Fixture(Model):
    __module_type__: ClassVar[ModuleType] = ...
    __constraints__: ClassVar[list[UniqueConstraint]] = ...
    class_name: str | None = ...
    order: float | None = ...
    external_id: str = ...
    data: dict[str, Any | None] = ...
    @classmethod
    def _non_empty_keys_data(cls, value: Any) -> Any: ...
