"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .conversationlogobject import ConversationLogObject, ConversationLogObjectTypedDict
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel


class ConversationLogResponseLinksTypedDict(TypedDict):
    next: NotRequired[str]
    prev: NotRequired[str]


class ConversationLogResponseLinks(BaseModel):
    next: Optional[str] = None

    prev: Optional[str] = None


class ConversationLogResponseMetaTypedDict(TypedDict):
    after_cursor: NotRequired[str]
    before_cursor: NotRequired[str]
    has_more: NotRequired[bool]


class ConversationLogResponseMeta(BaseModel):
    after_cursor: Optional[str] = None

    before_cursor: Optional[str] = None

    has_more: Optional[bool] = None


class ConversationLogResponseTypedDict(TypedDict):
    events: NotRequired[List[ConversationLogObjectTypedDict]]
    links: NotRequired[ConversationLogResponseLinksTypedDict]
    meta: NotRequired[ConversationLogResponseMetaTypedDict]


class ConversationLogResponse(BaseModel):
    events: Optional[List[ConversationLogObject]] = None

    links: Optional[ConversationLogResponseLinks] = None

    meta: Optional[ConversationLogResponseMeta] = None
