"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .organizationsubscriptionobject import (
    OrganizationSubscriptionObject,
    OrganizationSubscriptionObjectTypedDict,
)
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel


class OrganizationSubscriptionResponseTypedDict(TypedDict):
    organization_subscription: NotRequired[OrganizationSubscriptionObjectTypedDict]


class OrganizationSubscriptionResponse(BaseModel):
    organization_subscription: Optional[OrganizationSubscriptionObject] = None
