"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zendesk.types import BaseModel
from zendesk.utils import FieldMetadata, QueryParamMetadata


class ShowManyUsersRequestTypedDict(TypedDict):
    ids: NotRequired[str]
    r"""Accepts a comma-separated list of up to 100 user ids.

    """
    external_ids: NotRequired[str]
    r"""Accepts a comma-separated list of up to 100 external ids.

    """


class ShowManyUsersRequest(BaseModel):
    ids: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Accepts a comma-separated list of up to 100 user ids.

    """

    external_ids: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Accepts a comma-separated list of up to 100 external ids.

    """
