"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .ticketskipobject import TicketSkipObject, TicketSkipObjectTypedDict
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel


class TicketSkipCreationTypedDict(TypedDict):
    skip: NotRequired[TicketSkipObjectTypedDict]


class TicketSkipCreation(BaseModel):
    skip: Optional[TicketSkipObject] = None
