# Generated by Django 5.1.2 on 2024-11-11 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255, null=True)),
                ('payload', models.JSONField(default=None, null=True)),
                ('received_at', models.DateTimeField(help_text='Date and time event was received')),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.PositiveBigIntegerField(unique=True)),
                ('data', models.JSONField(default=dict)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_id', models.PositiveBigIntegerField(unique=True)),
                ('repository_node_id', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='django_github_app.installation')),
            ],
            options={
                'verbose_name_plural': 'repositories',
            },
        ),
    ]
