"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Any, Dict, List, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel


class ListMacroActionDefinitionsDefinitionsTypedDict(TypedDict):
    actions: NotRequired[List[Dict[str, Any]]]


class ListMacroActionDefinitionsDefinitions(BaseModel):
    actions: Optional[List[Dict[str, Any]]] = None


class ListMacroActionDefinitionsResponseTypedDict(TypedDict):
    r"""Success Response"""

    definitions: NotRequired[ListMacroActionDefinitionsDefinitionsTypedDict]


class ListMacroActionDefinitionsResponse(BaseModel):
    r"""Success Response"""

    definitions: Optional[ListMacroActionDefinitionsDefinitions] = None
