"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel


class RenewSessionResponseTypedDict(TypedDict):
    authenticity_token: NotRequired[str]
    r"""A token of authenticity for the request"""


class RenewSessionResponse(BaseModel):
    authenticity_token: Optional[str] = None
    r"""A token of authenticity for the request"""
