"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel


class TriggerCategoryTypedDict(TypedDict):
    created_at: NotRequired[str]
    id: NotRequired[str]
    name: NotRequired[str]
    position: NotRequired[int]
    updated_at: NotRequired[str]


class TriggerCategory(BaseModel):
    created_at: Optional[str] = None

    id: Optional[str] = None

    name: Optional[str] = None

    position: Optional[int] = None

    updated_at: Optional[str] = None
