# Stub file for type hints

from dataclasses import dataclass
from typing import Dict, ClassVar, List, Any

class CSThemeItem:
    _fields: ClassVar[List[str]]
    def __init__(self, dat: Dict[str, Any] = None, default_dat: Dict[str, Any] = None): ...
    def __getattr__(self, name: str): ...
    def __setattr__(self, name: str, value: Any): ...
    def to_dict(self): ...
    def values(self): ...
