# coding: utf-8

"""
    竹园污水项目

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from dhicn_zyws_service.configuration import Configuration


class SearchOutput(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'indicators': 'list[SearchIndicator]',
        'measure_ts_data': 'list[TimeseriesBatchForV3Output]',
        'model_ts_data': 'list[ModelResultOutput]'
    }

    attribute_map = {
        'indicators': 'indicators',
        'measure_ts_data': 'measureTsData',
        'model_ts_data': 'modelTsData'
    }

    def __init__(self, indicators=None, measure_ts_data=None, model_ts_data=None, local_vars_configuration=None):  # noqa: E501
        """SearchOutput - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._indicators = None
        self._measure_ts_data = None
        self._model_ts_data = None
        self.discriminator = None

        self.indicators = indicators
        self.measure_ts_data = measure_ts_data
        self.model_ts_data = model_ts_data

    @property
    def indicators(self):
        """Gets the indicators of this SearchOutput.  # noqa: E501

        查询的指标  # noqa: E501

        :return: The indicators of this SearchOutput.  # noqa: E501
        :rtype: list[SearchIndicator]
        """
        return self._indicators

    @indicators.setter
    def indicators(self, indicators):
        """Sets the indicators of this SearchOutput.

        查询的指标  # noqa: E501

        :param indicators: The indicators of this SearchOutput.  # noqa: E501
        :type: list[SearchIndicator]
        """

        self._indicators = indicators

    @property
    def measure_ts_data(self):
        """Gets the measure_ts_data of this SearchOutput.  # noqa: E501

        实测历史数据  # noqa: E501

        :return: The measure_ts_data of this SearchOutput.  # noqa: E501
        :rtype: list[TimeseriesBatchForV3Output]
        """
        return self._measure_ts_data

    @measure_ts_data.setter
    def measure_ts_data(self, measure_ts_data):
        """Sets the measure_ts_data of this SearchOutput.

        实测历史数据  # noqa: E501

        :param measure_ts_data: The measure_ts_data of this SearchOutput.  # noqa: E501
        :type: list[TimeseriesBatchForV3Output]
        """

        self._measure_ts_data = measure_ts_data

    @property
    def model_ts_data(self):
        """Gets the model_ts_data of this SearchOutput.  # noqa: E501

        模拟历史数据  # noqa: E501

        :return: The model_ts_data of this SearchOutput.  # noqa: E501
        :rtype: list[ModelResultOutput]
        """
        return self._model_ts_data

    @model_ts_data.setter
    def model_ts_data(self, model_ts_data):
        """Sets the model_ts_data of this SearchOutput.

        模拟历史数据  # noqa: E501

        :param model_ts_data: The model_ts_data of this SearchOutput.  # noqa: E501
        :type: list[ModelResultOutput]
        """

        self._model_ts_data = model_ts_data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SearchOutput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SearchOutput):
            return True

        return self.to_dict() != other.to_dict()
