# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from perian.models.instance_type_view import InstanceTypeView
from perian.models.pagination_metadata import PaginationMetadata
from typing import Optional, Set
from typing_extensions import Self

class GetInstanceTypesSuccess(BaseModel):
    """
    Response model for successful instance type request.
    """ # noqa: E501
    status: Optional[StrictStr] = 'Success'
    message: Optional[StrictStr] = 'Operation was successful'
    detail: Optional[StrictStr] = ''
    status_code: Optional[StrictInt] = 200
    limit: Optional[StrictInt] = 0
    no: Optional[StrictInt] = 0
    instance_types: Optional[List[InstanceTypeView]] = None
    pagination: Optional[PaginationMetadata] = None
    __properties: ClassVar[List[str]] = ["status", "message", "detail", "status_code", "limit", "no", "instance_types", "pagination"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetInstanceTypesSuccess from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in instance_types (list)
        _items = []
        if self.instance_types:
            for _item in self.instance_types:
                if _item:
                    _items.append(_item.to_dict())
            _dict['instance_types'] = _items
        # override the default output from pydantic by calling `to_dict()` of pagination
        if self.pagination:
            _dict['pagination'] = self.pagination.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetInstanceTypesSuccess from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status") if obj.get("status") is not None else 'Success',
            "message": obj.get("message") if obj.get("message") is not None else 'Operation was successful',
            "detail": obj.get("detail") if obj.get("detail") is not None else '',
            "status_code": obj.get("status_code") if obj.get("status_code") is not None else 200,
            "limit": obj.get("limit") if obj.get("limit") is not None else 0,
            "no": obj.get("no") if obj.get("no") is not None else 0,
            "instance_types": [InstanceTypeView.from_dict(_item) for _item in obj["instance_types"]] if obj.get("instance_types") is not None else None,
            "pagination": PaginationMetadata.from_dict(obj["pagination"]) if obj.get("pagination") is not None else None
        })
        return _obj


