"""
This module implements Cointegration-based Statistical Arbitrage strategies.
"""

from quantmllib.cointegration_approach.coint_sim import CointegrationSimulation
from quantmllib.cointegration_approach.engle_granger import EngleGrangerPortfolio
from quantmllib.cointegration_approach.johansen import JohansenPortfolio
from quantmllib.cointegration_approach.minimum_profit import MinimumProfit
from quantmllib.cointegration_approach.multi_coint import MultivariateCointegration
from quantmllib.cointegration_approach.sparse_mr_portfolio import SparseMeanReversionPortfolio
from quantmllib.cointegration_approach.utils import get_half_life_of_mean_reversion, get_hurst_exponent
