# Generated by Django 4.2 on 2024-09-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0006_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortCut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('url', models.CharField(max_length=100, verbose_name='url')),
                ('httpmethod', models.IntegerField(choices=[(0, 'GET'), (1, 'POST'), (2, 'DELETE')], default=0, verbose_name='http method')),
                ('parameters', models.TextField(blank=True, verbose_name='parameters')),
                ('order_key', models.IntegerField(default=None, null=True, verbose_name='order key')),
            ],
            options={
                'verbose_name': 'short-cut',
                'verbose_name_plural': 'short-cuts',
                'ordering': ['order_key'],
                'default_permissions': [],
            },
        ),
    ]
