"""
    ELEMENTS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elements_sdk
from elements_sdk.model.ldap_server import LDAPServer
globals()['LDAPServer'] = LDAPServer
from elements_sdk.model.elements_user_detail import ElementsUserDetail


class TestElementsUserDetail(unittest.TestCase):
    """ElementsUserDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testElementsUserDetail(self):
        """Test ElementsUserDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ElementsUserDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
