# coding: utf-8

"""
    Ringer Business API

    This API provides comprehensive endpoints for the Ringer Business system. It includes functionality for managing customer accounts, addresses, sites, phone numbers, payments, users, and other business resources.  Operations typically require authentication and appropriate permissions. 

    The version of the OpenAPI document: 1.0.6
    Contact: support@ringer.tel
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ringer_business.models.schemas_site_destination import SchemasSiteDestination

class TestSchemasSiteDestination(unittest.TestCase):
    """SchemasSiteDestination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SchemasSiteDestination:
        """Test SchemasSiteDestination
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SchemasSiteDestination`
        """
        model = SchemasSiteDestination()
        if include_optional:
            return SchemasSiteDestination(
                name = 'Main Menu (menu:main_menu)',
                code = 'menu:main_menu'
            )
        else:
            return SchemasSiteDestination(
                name = 'Main Menu (menu:main_menu)',
                code = 'menu:main_menu',
        )
        """

    def testSchemasSiteDestination(self):
        """Test SchemasSiteDestination"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
