from collections import Counter
import datetime as dt
from pathlib import Path

import polars as pl

from .runtime import TestCase

from shantay.dsa_sor import StatementsOfReasons
from shantay.framing import finalize
from shantay.metadata import Metadata
from shantay.model import Coverage, Daily, MetadataEntry, Storage
from shantay.processor import Processor
from shantay.schema import StatementCategoryProtectionOfMinors
from shantay.stats import Collector

ROOT = Path(__file__).parent
FIXTURE = ROOT / "fixture"
ARCHIVE = FIXTURE / "archive"

# We never copy the parquet files out of staging.
# So we only need ARCHIVE and STAGING.
STAGING = ROOT / "tmp"
LOGFILE = STAGING / "log.log"

ZIP_FILES = [
    "sor-global-2024-03-14-full-00000.csv.zip",
    "sor-global-2024-03-14-full-00001.csv.zip",
]

CSV_FILES = [
    "sor-global-2024-03-14-full-00000-00000.csv",
    "sor-global-2024-03-14-full-00000-00001.csv",
    "sor-global-2024-03-14-full-00001-00000.csv",
    "sor-global-2024-03-14-full-00001-00001.csv",
]


class TestDistill(TestCase):

    def test_extraction(self):
        self.maxDiff = None  # When something goes wrong, we want to see *all* about it
        with self.subTest("set up metadata, runner, and release"):
            dataset = StatementsOfReasons()
            storage = Storage(
                archive_root=ARCHIVE, extract_root=STAGING, staging_root=STAGING
            )
            release = Daily(2024, 3, 14)
            coverage = Coverage(release, release, StatementCategoryProtectionOfMinors)
            metadata = Metadata(StatementCategoryProtectionOfMinors, {})
            processor = Processor(
                dataset=dataset,
                storage=storage,
                coverage=coverage,
                metadata=metadata,
            )

            digest = release.parent_directory / dataset.digest_name(release)
            archive = release.parent_directory / dataset.archive_name(release)

        with self.subTest("stage archive by copying fixture"):
            self.assertFalse((STAGING / digest).exists())
            self.assertFalse((STAGING / archive).exists())
            processor.stage_archive(release)
            self.assertTrue((STAGING / digest).exists())
            self.assertTrue((STAGING / archive).exists())
            self.assertFileEqual(ARCHIVE / digest, STAGING / digest)
            self.assertFileEqual(ARCHIVE / archive, STAGING / archive)

        with self.subTest("determine archived files"):
            filenames = processor.list_archived_files(STAGING, release)
            self.assertListEqual(filenames, ZIP_FILES)

        with self.subTest("unarchive first of two CSV files"):
            workdir = STAGING / release.temp_directory
            self.assertFalse(workdir.exists())

            processor.unarchive_file(STAGING, release, 0, ZIP_FILES[0])
            self.assertTrue(workdir.exists())
            self.assertListEqual(
                sorted(p.name for p in workdir.glob("*")), CSV_FILES[:2]
            )
            self.assertFileEqual(workdir / CSV_FILES[0], FIXTURE / "csv" / CSV_FILES[0])
            self.assertFileEqual(workdir / CSV_FILES[1], FIXTURE / "csv" / CSV_FILES[1])

        with self.subTest("determine row counts"):
            glob = f"{STAGING / release.temp_directory}/*.csv"

            total_rows = keyword_rows = 0
            for csv_file in sorted(
                (STAGING / release.temp_directory).glob("*.csv")
            ):
                tl, kw = dataset.get_total_row_counts(csv_file)
                total_rows += tl
                keyword_rows += kw

            self.assertEqual(total_rows, 100)
            self.assertEqual(keyword_rows, 12)

        with self.subTest("distill first batch of category data"):
            frame = dataset._read_rows(
                csv_files=glob,
                release=release,
                index=0,
                name=ZIP_FILES[0],
                category=StatementCategoryProtectionOfMinors,
            )
            dataset._validate_schema(frame)

            counters = Counter(batch_count=2)
            counters += dataset._assemble_frame_counters(
                frame, total_rows, keyword_rows
            )
            self.assertEqual(counters["batch_count"], 2)
            self.assertEqual(counters["total_rows"], 100)
            self.assertEqual(counters["total_rows_with_keywords"], 12)
            self.assertEqual(counters["batch_rows"], 8)
            self.assertEqual(counters["batch_rows_with_keywords"], 2)

            framedir = STAGING / release.directory
            self.assertFalse(framedir.exists())
            framedir.mkdir(parents=True)
            batch0 = framedir / release.batch_file(0)
            # Ensure that writing does not fail
            frame.write_parquet(batch0)

            self.assertFrameEqual(
                frame,
                pl.read_parquet(FIXTURE / release.batch_file(0))
            )

        with self.subTest("extract second batch of category data"):
            batch1 = STAGING / release.directory / release.batch_file(1)
            self.assertFalse(batch1.exists())

            processor.unarchive_file(STAGING, release, 1, ZIP_FILES[1])
            digest, more_counters = dataset.distill_category_data(
                root=STAGING,
                release=release,
                index=1,
                name=ZIP_FILES[1],
                category=StatementCategoryProtectionOfMinors,
            )

            self.assertListEqual(sorted(p.name for p in workdir.glob("*")), CSV_FILES)
            self.assertFileEqual(workdir / CSV_FILES[2], FIXTURE / "csv" / CSV_FILES[2])
            self.assertFileEqual(workdir / CSV_FILES[3], FIXTURE / "csv" / CSV_FILES[3])

            counters += more_counters
            self.assertEqual(counters["batch_count"], 2)
            self.assertEqual(counters["total_rows"], 100 + 102)
            self.assertEqual(counters["total_rows_with_keywords"], 12 + 1)
            self.assertEqual(counters["batch_rows"], 8 + 9)
            self.assertEqual(counters["batch_rows_with_keywords"], 2 + 0)

            self.assertTrue(batch1.exists())
            self.assertFrameEqual(
                pl.read_parquet(batch1),
                pl.read_parquet(FIXTURE / release.batch_file(1))
            )

        with self.subTest("analyze release data"):
            collector = Collector()
            metadata_entry: MetadataEntry = {
                "batch_count": 2,
                "total_rows": 665,
                "total_rows_with_keywords": 212,
            }
            dataset.summarize_release(
                STAGING,
                release,
                StatementCategoryProtectionOfMinors,
                metadata_entry,
                collector,
            )

            frame = finalize(collector.frame())
            frame_data = frame.to_dict(as_series=False)

            # import pprint

            # with open("data.txt", mode="w", encoding="utf8") as file:
            #     pprint.pprint(frame_data, stream=file)

            self.assertEqual(frame_data, EXPECTED_ANALYSIS)

            # Write to parquet
            frame.write_parquet(STAGING / f"{coverage.stem()}.parquet")

        with self.subTest("check log file"):
            lines = LOGFILE.read_text("utf8").splitlines(keepends=True)

            offset = -1
            for offset, line in enumerate(lines):
                if 'staged file="sor-global-2024-03-14-full.zip"' in line:
                    break

            self.assertNotEqual(offset, -1)
            self.assertTrue(offset + 38 <= len(lines))
            self.assertIn("staged file", lines[offset + 0])
            self.assertIn("validate release", lines[offset + 1])
            self.assertIn("validated release", lines[offset + 2])
            self.assertIn('unarchived type="nested archive"', lines[offset + 3])
            self.assertIn(
                'counted rows=50, rows-with-keywords=4, file='
                '"sor-global-2024-03-14-full-00000-00000.csv"',
                lines[offset + 4]
            )
            self.assertIn(
                'counted rows=50, rows-with-keywords=8, file='
                '"sor-global-2024-03-14-full-00000-00001.csv"',
                lines[offset + 5]
            )
            self.assertIn("ingested rows=8", lines[offset + 6])
            self.assertIn('unarchived type="nested archive"', lines[offset + 7])
            self.assertIn(
                'counted rows=50, rows-with-keywords=0, file='
                '"sor-global-2024-03-14-full-00001-00000.csv"',
                lines[offset + 8]
            )
            self.assertIn(
                'counted rows=52, rows-with-keywords=1, file='
                '"sor-global-2024-03-14-full-00001-00001.csv"',
                lines[offset + 9]
            )
            offset += 10
            # Trying to parse both CSV files in one Pola.rs operation fails:
            self.assertIn(
                'shantay︙WARNING︙failed to read CSV with strategy=1, using="globbing Pola.rs"',
                lines[offset + 0],
            )
            self.assertTrue(lines[offset + 1].startswith("Traceback"))
            self.assertTrue(lines[offset + 2].startswith("  File"))
            self.assertTrue(lines[offset + 3].startswith("    ).collect()"))
            self.assertTrue(lines[offset + 4].startswith("      ^^^^^^^"))
            self.assertTrue(lines[offset + 5].startswith("  File"))
            self.assertTrue(lines[offset + 6].startswith("    return function(*args, **kwargs)"))
            self.assertTrue(lines[offset + 7].startswith("           ^^^^^^^^^^^^^^^^^^^^^^^^^"))
            self.assertTrue(lines[offset + 8].startswith("  File"))
            self.assertTrue(lines[offset + 9].startswith("    return function(*args, **kwargs)"))
            self.assertTrue(lines[offset + 10].startswith("           ^^^^^^^^^^^^^^^^^^^^^^^^^"))
            self.assertTrue(lines[offset + 11].startswith("  File"))
            self.assertTrue(lines[offset + 12].startswith("    return wrap_df(ldf.collect(engine, callback))"))
            self.assertTrue(lines[offset + 13].startswith("                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"))

            # Since the particulars of the traceback have changed over time,
            # make offsets relative to the next log line.
            offset = offset + 14

            self.assertTrue(
                lines[offset].startswith(
                    "polars.exceptions.ComputeError: could not parse"
                )
            )
            self.assertTrue(lines[offset + 1].startswith(""))
            self.assertTrue(
                lines[offset + 2].startswith(
                    "The current offset in the file is 131 bytes"
                )
            )
            self.assertTrue(lines[offset + 3].startswith(""))
            self.assertTrue(lines[offset + 4].startswith("You might want to try"))
            self.assertTrue(lines[offset + 5].startswith("- increasing"))
            self.assertTrue(lines[offset + 6].startswith("- specifying"))
            self.assertTrue(lines[offset + 7].startswith("- setting"))
            self.assertTrue(lines[offset + 8].startswith("- adding"))
            self.assertTrue(lines[offset + 9].startswith(""))
            self.assertTrue(
                lines[offset + 10].startswith("Original error: ```invalid csv file")
            )
            self.assertTrue(lines[offset + 11].startswith(""))
            self.assertTrue(lines[offset + 12].startswith('Field `"Napodobňovanie'))
            # Parsing the first CSV file by itself with Pola.rs works:
            self.assertIn(
                'ingested rows=8, strategy=2, using="Pola.rs"', lines[offset + 13]
            )
            # Parsing the second CSV file by itself with Pola.rs fails:
            self.assertIn(
                'failed to read CSV with strategy=2, using="Pola.rs"',
                lines[offset + 14],
            )
            # Parsing the second CSV fail by itself with Python's csv works:
            self.assertIn(
                'ingested rows=1, strategy=3, using="Python\'s CSV module"',
                lines[offset + 15],
            )


# Shantay's current analysis data format is a very long table...
EXPECTED_ANALYSIS = {
    "column": [
        "batch_count",
        "batch_rows",
        "batch_rows_with_keywords",
        "total_rows",
        "total_rows_with_keywords",
        "rows",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_visibility",
        "decision_visibility_other",
        "visibility_restriction_duration",
        "visibility_restriction_duration",
        "decision_monetary",
        "decision_monetary_other",
        "monetary_restriction_duration",
        "monetary_restriction_duration",
        "decision_provision",
        "service_restriction_duration",
        "service_restriction_duration",
        "decision_account",
        "account_restriction_duration",
        "account_restriction_duration",
        "account_type",
        "decision_ground",
        "incompatible_content_illegal",
        "category",
        "category_addition",
        "category_addition",
        "category_addition",
        "category_addition",
        "category_specification",
        "category_specification",
        "category_specification",
        "category_specification",
        "category_specification_other",
        "content_type",
        "content_type",
        "content_type",
        "content_type",
        "content_type",
        "content_type_other",
        "content_language",
        "moderation_delay",
        "moderation_delay",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "disclosure_delay",
        "disclosure_delay",
        "source_type",
        "automated_detection",
        "automated_decision",
        "rows",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_visibility",
        "decision_visibility",
        "decision_visibility_other",
        "visibility_restriction_duration",
        "visibility_restriction_duration",
        "decision_monetary",
        "decision_monetary_other",
        "monetary_restriction_duration",
        "monetary_restriction_duration",
        "decision_provision",
        "service_restriction_duration",
        "service_restriction_duration",
        "decision_account",
        "decision_account",
        "account_restriction_duration",
        "account_restriction_duration",
        "account_type",
        "decision_ground",
        "incompatible_content_illegal",
        "category",
        "category_addition",
        "category_addition",
        "category_addition",
        "category_addition",
        "category_specification",
        "category_specification",
        "category_specification",
        "category_specification",
        "category_specification",
        "category_specification",
        "category_specification_other",
        "content_type",
        "content_type",
        "content_type",
        "content_type",
        "content_type",
        "content_type_other",
        "content_type_other",
        "content_language",
        "moderation_delay",
        "moderation_delay",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "disclosure_delay",
        "disclosure_delay",
        "source_type",
        "source_type",
        "automated_detection",
        "automated_detection",
        "automated_decision",
        "rows",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_visibility",
        "decision_visibility_other",
        "visibility_restriction_duration",
        "visibility_restriction_duration",
        "decision_monetary",
        "decision_monetary_other",
        "monetary_restriction_duration",
        "monetary_restriction_duration",
        "decision_provision",
        "service_restriction_duration",
        "service_restriction_duration",
        "decision_account",
        "account_restriction_duration",
        "account_restriction_duration",
        "account_type",
        "decision_ground",
        "incompatible_content_illegal",
        "category",
        "category_addition",
        "category_addition",
        "category_addition",
        "category_addition",
        "category_specification",
        "category_specification",
        "category_specification",
        "category_specification",
        "category_specification_other",
        "content_type",
        "content_type",
        "content_type",
        "content_type",
        "content_type_other",
        "content_language",
        "moderation_delay",
        "moderation_delay",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "disclosure_delay",
        "disclosure_delay",
        "source_type",
        "automated_detection",
        "automated_decision",
        "rows",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_type",
        "decision_visibility",
        "decision_visibility",
        "decision_visibility",
        "decision_visibility_other",
        "decision_visibility_other",
        "visibility_restriction_duration",
        "visibility_restriction_duration",
        "decision_monetary",
        "decision_monetary_other",
        "monetary_restriction_duration",
        "monetary_restriction_duration",
        "decision_provision",
        "service_restriction_duration",
        "service_restriction_duration",
        "decision_account",
        "account_restriction_duration",
        "account_restriction_duration",
        "account_type",
        "decision_ground",
        "incompatible_content_illegal",
        "category",
        "category_addition",
        "category_addition",
        "category_addition",
        "category_addition",
        "category_specification",
        "category_specification",
        "category_specification",
        "category_specification",
        "category_specification_other",
        "content_type",
        "content_type",
        "content_type",
        "content_type",
        "content_type",
        "content_type_other",
        "content_language",
        "moderation_delay",
        "moderation_delay",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "territorial_scope",
        "disclosure_delay",
        "disclosure_delay",
        "source_type",
        "automated_detection",
        "automated_decision",
        "automated_decision",
    ],
    "count": [
        2,
        17,
        2,
        665,
        212,
        1,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        0,
        0,
        1,
        1,
        0,
        0,
        1,
        0,
        0,
        1,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        1,
        2,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        29,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        1,
        1,
        1,
        2,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        2,
        0,
        0,
        2,
        2,
        0,
        0,
        2,
        0,
        0,
        1,
        1,
        0,
        0,
        2,
        2,
        2,
        2,
        0,
        0,
        0,
        2,
        3,
        0,
        2,
        1,
        1,
        1,
        2,
        2,
        0,
        2,
        1,
        1,
        1,
        1,
        2,
        2,
        0,
        2,
        0,
        2,
        2,
        2,
        0,
        1,
        1,
        1,
        1,
        2,
        1,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        0,
        0,
        1,
        1,
        0,
        0,
        1,
        0,
        0,
        1,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        1,
        1,
        0,
        1,
        1,
        1,
        1,
        0,
        1,
        1,
        1,
        1,
        1,
        0,
        1,
        0,
        1,
        1,
        1,
        0,
        1,
        1,
        1,
        14,
        0,
        14,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        9,
        4,
        1,
        9,
        5,
        0,
        0,
        14,
        14,
        0,
        0,
        14,
        0,
        0,
        14,
        0,
        0,
        14,
        14,
        14,
        14,
        0,
        0,
        0,
        14,
        0,
        0,
        0,
        14,
        14,
        14,
        0,
        14,
        13,
        1,
        14,
        14,
        14,
        0,
        14,
        0,
        14,
        14,
        14,
        0,
        14,
        14,
        10,
        4,
    ],
    "end_date": [
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
    ],
    "entity": [
        None,
        None,
        None,
        None,
        None,
        None,
        "is_null",
        "vis",
        "mon",
        "vis_mon",
        "pro",
        "vis_pro",
        "mon_pro",
        "vis_mon_pro",
        "acc",
        "vis_acc",
        "mon_acc",
        "vis_mon_acc",
        "pro_acc",
        "vis_pro_acc",
        "mon_pro_acc",
        "vis_mon_pro_acc",
        None,
        None,
        None,
        "null_bc_negative",
        None,
        None,
        None,
        "null_bc_negative",
        None,
        None,
        "null_bc_negative",
        None,
        None,
        "null_bc_negative",
        None,
        None,
        None,
        None,
        "elements",
        "elements_per_row",
        "rows_with_elements",
        None,
        "elements",
        "elements_per_row",
        "rows_with_elements",
        None,
        None,
        "elements",
        "elements_per_row",
        "rows_with_elements",
        None,
        None,
        None,
        None,
        None,
        "null_bc_negative",
        "elements",
        "elements_per_row",
        "rows_with_elements",
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        "null_bc_negative",
        None,
        None,
        None,
        None,
        "is_null",
        "vis",
        "mon",
        "vis_mon",
        "pro",
        "vis_pro",
        "mon_pro",
        "vis_mon_pro",
        "acc",
        "vis_acc",
        "mon_acc",
        "vis_mon_acc",
        "pro_acc",
        "vis_pro_acc",
        "mon_pro_acc",
        "vis_mon_pro_acc",
        None,
        None,
        None,
        None,
        "null_bc_negative",
        None,
        None,
        None,
        "null_bc_negative",
        None,
        None,
        "null_bc_negative",
        None,
        None,
        None,
        "null_bc_negative",
        None,
        None,
        None,
        None,
        "elements",
        "elements_per_row",
        "rows_with_elements",
        None,
        "elements",
        "elements_per_row",
        "rows_with_elements",
        None,
        None,
        None,
        None,
        "elements",
        "elements_per_row",
        "rows_with_elements",
        None,
        None,
        None,
        None,
        None,
        None,
        "null_bc_negative",
        "elements",
        "elements_per_row",
        "rows_with_elements",
        None,
        None,
        "null_bc_negative",
        None,
        None,
        None,
        None,
        None,
        None,
        "is_null",
        "vis",
        "mon",
        "vis_mon",
        "pro",
        "vis_pro",
        "mon_pro",
        "vis_mon_pro",
        "acc",
        "vis_acc",
        "mon_acc",
        "vis_mon_acc",
        "pro_acc",
        "vis_pro_acc",
        "mon_pro_acc",
        "vis_mon_pro_acc",
        None,
        None,
        None,
        "null_bc_negative",
        None,
        None,
        None,
        "null_bc_negative",
        None,
        None,
        "null_bc_negative",
        None,
        None,
        "null_bc_negative",
        None,
        None,
        None,
        None,
        "elements",
        "elements_per_row",
        "rows_with_elements",
        None,
        "elements",
        "elements_per_row",
        "rows_with_elements",
        None,
        None,
        "elements",
        "elements_per_row",
        "rows_with_elements",
        None,
        None,
        None,
        None,
        "null_bc_negative",
        "elements",
        "elements_per_row",
        "rows_with_elements",
        None,
        None,
        "null_bc_negative",
        None,
        None,
        None,
        None,
        "is_null",
        "vis",
        "mon",
        "vis_mon",
        "pro",
        "vis_pro",
        "mon_pro",
        "vis_mon_pro",
        "acc",
        "vis_acc",
        "mon_acc",
        "vis_mon_acc",
        "pro_acc",
        "vis_pro_acc",
        "mon_pro_acc",
        "vis_mon_pro_acc",
        None,
        None,
        None,
        None,
        None,
        None,
        "null_bc_negative",
        None,
        None,
        None,
        "null_bc_negative",
        None,
        None,
        "null_bc_negative",
        None,
        None,
        "null_bc_negative",
        None,
        None,
        None,
        None,
        "elements",
        "elements_per_row",
        "rows_with_elements",
        None,
        "elements",
        "elements_per_row",
        "rows_with_elements",
        None,
        None,
        "elements",
        "elements_per_row",
        "rows_with_elements",
        None,
        None,
        None,
        None,
        None,
        "null_bc_negative",
        "elements",
        "elements_per_row",
        "rows_with_elements",
        None,
        None,
        "null_bc_negative",
        None,
        None,
        None,
        None,
    ],
    "max": [
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        2,
        None,
        None,
        None,
        None,
        None,
        0,
        None,
        None,
        29,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        86582,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        2,
        None,
        None,
        None,
        None,
        None,
        None,
        1,
        None,
        None,
        None,
        None,
        None,
        None,
        5702400,
        None,
        None,
        1,
        None,
        None,
        279,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        1,
        None,
        None,
        None,
        None,
        1,
        None,
        None,
        None,
        None,
        0,
        None,
        None,
        1,
        None,
        None,
        95,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        1,
        None,
        None,
        None,
        None,
        None,
        65059200,
        None,
        None,
        1,
        None,
        None,
        172832,
        None,
        None,
        None,
        None,
        None,
    ],
    "mean": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        86582,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2851200,
        0,
        0,
        0,
        0,
        0,
        187,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        95,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        8343771,
        0,
        0,
        0,
        0,
        0,
        105219,
        0,
        0,
        0,
        0,
        0,
    ],
    "min": [
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        0,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        86582,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        0,
        None,
        None,
        None,
        None,
        None,
        95,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        0,
        None,
        None,
        None,
        None,
        None,
        95,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        0,
        None,
        None,
        None,
        None,
        None,
        86410,
        None,
        None,
        None,
        None,
        None,
    ],
    "platform": [
        None,
        None,
        None,
        None,
        None,
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Google Shopping",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "Snapchat",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
        "TikTok",
    ],
    "start_date": [
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
        dt.date(2024, 3, 14),
    ],
    "tag": [
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        None,
        None,
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
    ],
    "text": [
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        "Account",
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        "Video not eligible for recommendation in the For You feed",
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    "variant": [
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        "DECISION_VISIBILITY_CONTENT_REMOVED",
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        "DECISION_GROUND_INCOMPATIBLE_CONTENT",
        None,
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        "CONTENT_TYPE_IMAGE",
        "CONTENT_TYPE_TEXT",
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        "AT",
        "BE",
        "BG",
        "CY",
        "CZ",
        "DE",
        "DK",
        "EE",
        "ES",
        "FI",
        "FR",
        "GR",
        "HR",
        "HU",
        "IE",
        "IS",
        "IT",
        "LT",
        "LU",
        "LV",
        "MT",
        "NL",
        "NO",
        "PL",
        "PT",
        "RO",
        "SE",
        "SI",
        "SK",
        None,
        None,
        "SOURCE_VOLUNTARY",
        "Yes",
        "AUTOMATED_DECISION_FULLY",
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        "DECISION_VISIBILITY_CONTENT_REMOVED",
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        "DECISION_ACCOUNT_SUSPENDED",
        None,
        None,
        None,
        "DECISION_GROUND_INCOMPATIBLE_CONTENT",
        "Yes",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        "KEYWORD_GROOMING_SEXUAL_ENTICEMENT_MINORS",
        "KEYWORD_AGE_SPECIFIC_RESTRICTIONS",
        None,
        None,
        None,
        None,
        "CONTENT_TYPE_IMAGE",
        "CONTENT_TYPE_OTHER",
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        "EEA",
        None,
        None,
        "SOURCE_VOLUNTARY",
        "SOURCE_ARTICLE_16",
        "Yes",
        "No",
        "AUTOMATED_DECISION_FULLY",
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        "DECISION_VISIBILITY_CONTENT_REMOVED",
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        "DECISION_GROUND_INCOMPATIBLE_CONTENT",
        "Yes",
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        "KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL",
        None,
        None,
        None,
        None,
        "CONTENT_TYPE_IMAGE",
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        "EEA",
        None,
        None,
        "SOURCE_VOLUNTARY",
        "Yes",
        "AUTOMATED_DECISION_FULLY",
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        "DECISION_VISIBILITY_OTHER",
        "DECISION_VISIBILITY_CONTENT_AGE_RESTRICTED",
        "DECISION_VISIBILITY_CONTENT_REMOVED",
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        "DECISION_GROUND_INCOMPATIBLE_CONTENT",
        None,
        "STATEMENT_CATEGORY_PROTECTION_OF_MINORS",
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        "CONTENT_TYPE_VIDEO",
        "CONTENT_TYPE_TEXT",
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        "EEA_no_IS",
        None,
        None,
        "SOURCE_VOLUNTARY",
        "Yes",
        "AUTOMATED_DECISION_FULLY",
        "AUTOMATED_DECISION_NOT_AUTOMATED",
    ],
}
