# Stub file for type hints

from typing import Union, Callable, Any
from PySide6.QtWidgets import QDialog, QLabel, QPushButton, QLayout
from PySide6.QtWidgets import QHBoxLayout, QVBoxLayout, QFrame
from PySide6.QtWidgets import QWidget, QGraphicsDropShadowEffect
from PySide6.QtCore import Qt
from PySide6.QtGui import QFont, QColor
from cesarview.helper.cs_colors import CSColors
from cesarview.theme import CSTheme

class CSBaseDialog:
    def __init__(self, width: int = None, height: int = None, bg_color: str = None, border_radius: int = None, border: str = None, margin: int = None, padding: int = None, shadowed: bool = True, title: str = None, title_color: str = None, title_close: str = None, title_close_hided: bool = False, title_close_callback: Callable[[], bool] = None, title_font: str = None, title_font_size: str = None, content: Union[QLayout, QWidget] = None, footer_btn_width: int = None, footer_btn_height: int = None, footer_btn_font_size: int = None, footer_btn_font_weight: int = None, footer_left_btn_text: str = None, footer_left_btn_text_color: str = None, footer_left_btn_bg_color: str = None, footer_left_btn_border: str = None, footer_left_btn_border_radius: int = None, footer_left_btn_callback: Callable[[], bool] = None, footer_left_btn_hided: bool = False, footer_right_btn_text: str = None, footer_right_btn_text_color: str = None, footer_right_btn_bg_color: str = None, footer_right_btn_border: str = None, footer_right_btn_border_radius: int = None, footer_right_btn_callback: Callable[[], bool] = None, footer_right_btn_hided: bool = False, parent: Any = None): ...
    def setup(self): ...
    def set_content_layout(self, layout: QLayout): ...
    def set_content_widget(self, widget: QWidget): ...
    def mousePressEvent(self, event): ...
    def mouseMoveEvent(self, event): ...
    def _on_btn_clicked_title(self): ...
    def _on_btn_clicked_left(self): ...
    def _on_btn_clicked_right(self): ...
