class TemplateEngineException(Exception): ...


class ProjectNotFoundErr(TemplateEngineException): ...


class FileFormatMismatch(TemplateEngineException): ...


class MetadataFileNotFoundErr(TemplateEngineException): ...


class UnsupportedFileExtension(TemplateEngineException): ...
