# coding: utf-8

"""
    EVE Stellar Information (ESI) - tranquility

    EVE ESI Python Client generated with openapi-generator with strong typing features.

    The version of the OpenAPI document: 2020-01-01
    Contact: morte1916@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from eve_esi_python.models.universe_ids_post import UniverseIdsPost

class TestUniverseIdsPost(unittest.TestCase):
    """UniverseIdsPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UniverseIdsPost:
        """Test UniverseIdsPost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UniverseIdsPost`
        """
        model = UniverseIdsPost()
        if include_optional:
            return UniverseIdsPost(
                agents = [
                    eve_esi_python.models.universe_ids_post_agents_inner.UniverseIdsPost_agents_inner(
                        id = 56, 
                        name = '', )
                    ],
                alliances = [
                    eve_esi_python.models.universe_ids_post_alliances_inner.UniverseIdsPost_alliances_inner(
                        id = 56, 
                        name = '', )
                    ],
                characters = [
                    eve_esi_python.models.universe_ids_post_characters_inner.UniverseIdsPost_characters_inner(
                        id = 56, 
                        name = '', )
                    ],
                constellations = [
                    eve_esi_python.models.universe_ids_post_constellations_inner.UniverseIdsPost_constellations_inner(
                        id = 56, 
                        name = '', )
                    ],
                corporations = [
                    eve_esi_python.models.universe_ids_post_corporations_inner.UniverseIdsPost_corporations_inner(
                        id = 56, 
                        name = '', )
                    ],
                factions = [
                    eve_esi_python.models.universe_ids_post_factions_inner.UniverseIdsPost_factions_inner(
                        id = 56, 
                        name = '', )
                    ],
                inventory_types = [
                    eve_esi_python.models.universe_ids_post_inventory_types_inner.UniverseIdsPost_inventory_types_inner(
                        id = 56, 
                        name = '', )
                    ],
                regions = [
                    eve_esi_python.models.universe_ids_post_regions_inner.UniverseIdsPost_regions_inner(
                        id = 56, 
                        name = '', )
                    ],
                stations = [
                    eve_esi_python.models.universe_ids_post_stations_inner.UniverseIdsPost_stations_inner(
                        id = 56, 
                        name = '', )
                    ],
                systems = [
                    eve_esi_python.models.universe_ids_post_systems_inner.UniverseIdsPost_systems_inner(
                        id = 56, 
                        name = '', )
                    ]
            )
        else:
            return UniverseIdsPost(
        )
        """

    def testUniverseIdsPost(self):
        """Test UniverseIdsPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
