# coding: utf-8

"""
    EVE Stellar Information (ESI) - tranquility

    EVE ESI Python Client generated with openapi-generator with strong typing features.

    The version of the OpenAPI document: 2020-01-01
    Contact: morte1916@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from eve_esi_python.models.killmails_killmail_id_killmail_hash_get_victim_items_inner_items_inner import KillmailsKillmailIdKillmailHashGetVictimItemsInnerItemsInner

class TestKillmailsKillmailIdKillmailHashGetVictimItemsInnerItemsInner(unittest.TestCase):
    """KillmailsKillmailIdKillmailHashGetVictimItemsInnerItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KillmailsKillmailIdKillmailHashGetVictimItemsInnerItemsInner:
        """Test KillmailsKillmailIdKillmailHashGetVictimItemsInnerItemsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KillmailsKillmailIdKillmailHashGetVictimItemsInnerItemsInner`
        """
        model = KillmailsKillmailIdKillmailHashGetVictimItemsInnerItemsInner()
        if include_optional:
            return KillmailsKillmailIdKillmailHashGetVictimItemsInnerItemsInner(
                flag = 56,
                item_type_id = 56,
                quantity_destroyed = 56,
                quantity_dropped = 56,
                singleton = 56
            )
        else:
            return KillmailsKillmailIdKillmailHashGetVictimItemsInnerItemsInner(
                flag = 56,
                item_type_id = 56,
                singleton = 56,
        )
        """

    def testKillmailsKillmailIdKillmailHashGetVictimItemsInnerItemsInner(self):
        """Test KillmailsKillmailIdKillmailHashGetVictimItemsInnerItemsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
