# coding: utf-8

"""
    EVE Stellar Information (ESI) - tranquility

    EVE ESI Python Client generated with openapi-generator with strong typing features.

    The version of the OpenAPI document: 2020-01-01
    Contact: morte1916@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from eve_esi_python.models.corporations_corporation_id_medals_issued_get_inner import CorporationsCorporationIdMedalsIssuedGetInner

class TestCorporationsCorporationIdMedalsIssuedGetInner(unittest.TestCase):
    """CorporationsCorporationIdMedalsIssuedGetInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CorporationsCorporationIdMedalsIssuedGetInner:
        """Test CorporationsCorporationIdMedalsIssuedGetInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CorporationsCorporationIdMedalsIssuedGetInner`
        """
        model = CorporationsCorporationIdMedalsIssuedGetInner()
        if include_optional:
            return CorporationsCorporationIdMedalsIssuedGetInner(
                character_id = 56,
                issued_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                issuer_id = 56,
                medal_id = 56,
                reason = '',
                status = 'private'
            )
        else:
            return CorporationsCorporationIdMedalsIssuedGetInner(
                character_id = 56,
                issued_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                issuer_id = 56,
                medal_id = 56,
                reason = '',
                status = 'private',
        )
        """

    def testCorporationsCorporationIdMedalsIssuedGetInner(self):
        """Test CorporationsCorporationIdMedalsIssuedGetInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
